### ISSUE TITLE
Question for tacocopter challenge

### ISSUE THREAD

**Issue by rstormsf** [procore/tacocopter#2]
@fairchild @bradurani 
1. There are 3 branches. Which one should I fork from? 
2. I'd better use https://eggerapps.at/postico/ for http://tacocopter.herokuapp.com/connecting instead of some online sql tool
3. Not sure what [slides](https://docs.google.com/presentation/d/1Y3gWwABlmSjAeZrBflAhUv-6m2nDRY8FYxvswJal4D0/edit?usp=sharing%22) are for while we have http://tacocopter.herokuapp.com/questions It seems like it's duplication of info

**Comment by fairchild** [comment]
We have also used this repo to teach an internal sql workshop. The readme is more oriented toward the workshop. Please consider the instructions in the email as the authoritative instructions.  You do not need the slides, and do not need to use any particular sql tool.  The sql tool suggestion was for the sql workshop, not for this coding challenge.

**Comment by rstormsf** [comment]
@fairchild 
I have completed the assignment: https://github.com/rstormsf/tacocopter-procore
Please let me know if I need to share access to more people

https://rstorm-tacocopter.herokuapp.com/

I've spend my Sunday to work on it.

**Comment by rstormsf** [comment]
What I personally found strange is that Store table has many duplicate names with different ids. At first, I was thinking that I'm not aggregating my data, then I realized that these are different ids
